use testdata;

CREATE TABLE `fct_profile` (
  `MSISDN` int(11) DEFAULT NULL,
  `PROFILE` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO fct_profile
SELECT e.MSISDN, CONCAT(e.CREDITSCORE,"|",e.ASSETS,"|",z.DISPINCOME,"|", p.CHURNRISK) AS PROFILE FROM src_external1 e INNER JOIN src_profile p ON e.MSISDN = p.MSISDN INNER JOIN src_zip z ON p.POSTALCODE = z.ZIPCODE;

SELECT * FROM fct_profile WHERE MSISDN IN (aaa)
SELECT SPRAYPRAYUPTAKE FROM src_marketinterest WHERE MARKETINTEREST = ''



SELECT MSISDN, SUM(DOWNLOAD_BYTES)/COUNT(1) AS DOWNLOAD_BYTES FROM src_xdr GROUP BY MSISDN
SELECT * FROM src_xdr