use testdata;

CREATE TABLE `fct_profile` (
  `MSISDN` int(11) DEFAULT NULL,
  `PROFILE` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

##Populate fct_profile
INSERT INTO fct_profile
SELECT e.MSISDN, CONCAT(e.CREDITSCORE,"|",e.ASSETS,"|",z.DISPINCOME,"|", p.CHURNRISK) AS PROFILE 
FROM src_external1 e INNER JOIN src_profile p ON e.MSISDN = p.MSISDN INNER JOIN src_zip z ON p.POSTALCODE = z.ZIPCODE;


##Populate external with missing msisdn records
INSERT INTO src_external1
SELECT MSISDN, FLOOR(RAND()*460)+400 AS CREDITSCORE,  FLOOR(RAND()*200000) AS ASSETS FROM
(
SELECT DISTINCT MSISDN FROM src_xdr
WHERE MSISDN NOT IN (SELECT MSISDN FROM src_external1)
) A

#Create temp table 
CREATE TABLE `tmp_msisdn` (
  `MSISDN` int(11) DEFAULT NULL
); 

#Insert MSISDN records
INSERT INTO tmp_msisdn
SELECT MSISDN FROM src_msisdn
WHERE MSISDN NOT IN (SELECT MSISDN FROM src_profile);

#Inset profile records
INSERT INTO src_profile
SELECT
MSISDN,
TRUNCATE(RAND()*200,2),
FLOOR(RAND()*48),
'No',
FLOOR(RAND()*3000),
FLOOR(RAND()*2000),
FLOOR(RAND()*50),
FLOOR(RAND()*200),
LPAD(FLOOR(RAND()*100000), 5, '0'),
TRUNCATE(RAND(),2)
FROM src_msisdn;

#Truncate already existing data in fct_profile
TRUNCATE TABLE fct_profile;

#Insert the records
INSERT INTO fct_profile
SELECT e.MSISDN, CONCAT(e.CREDITSCORE,"|",e.ASSETS,"|",z.DISPINCOME,"|", p.CHURNRISK) AS PROFILE 
FROM src_external1 e INNER JOIN src_profile p ON e.MSISDN = p.MSISDN INNER JOIN src_zip z ON p.POSTALCODE = z.ZIPCODE;

#Create index
CREATE UNIQUE INDEX ix_u
ON src_external1 ( MSISDN, CREDITSCORE,ASSETS);
CREATE UNIQUE INDEX ix_u
ON src_profile ( MSISDN, POSTALCODE,CHURNRISK);
CREATE UNIQUE INDEX ix_u
ON src_zip (ZIPCODE,DISPINCOME);

#Insert into fct_profile
INSERT INTO fct_profile
SELECT e.MSISDN, CONCAT(e.CREDITSCORE,"|",e.ASSETS,"|",FLOOR(RAND()*254233),"|", p.CHURNRISK) AS PROFILE 
FROM src_external1 e INNER JOIN src_profile p ON e.MSISDN = p.MSISDN #INNER JOIN src_zip z ON p.POSTALCODE = z.ZIPCODE;

#Fact table
INSERT INTO fct_profile
SELECT e.MSISDN, CONCAT(e.CREDITSCORE,"|",e.ASSETS,"|",FLOOR(RAND()*254233),"|", TRUNCATE(RAND(),4)) AS PROFILE 
FROM src_external1 e

#Create the index
CREATE UNIQUE INDEX ix_u
ON fct_profile (MSISDN, PROFILE);

#Creae the fact xdr
CREATE TABLE `fct_xdr` (
  `MSISDN` int(11) DEFAULT NULL,
  `IAB_TIER1` varchar(100) DEFAULT NULL,
  `DOWNLOAD_BYTES` int(11) DEFAULT NULL,
  `HOST` varchar(100) DEFAULT NULL
) 

#Insert the fact xdr
INSERT INTO fct_xdr
SELECT MSISDN,IAB_TIER1,DOWNLOAD_BYTES,HOST FROM src_xdr WHERE
IAB_TIER1 IN
(
"ACCESSORIES","ACCOUNTING","ADD","ADULT_EDUCATION","ARTS_CRAFTS","BARBECUES_GRILLING","CHRISTIANITY","EDUCATIONAL_INSTITUTIONS","ENTERTAINMENT_NEWS_CELEBRITY_SITES","ENTERTAINMENT_OTHER","FINANCIAL_PLANNING","HEALTH_LOWFAT_COOKING","INVESTING","LITERATURE_BOOKS","MOVIES","MUSIC","PRIVATE_SCHOOL","PSYCHOLOGY_PSYCHIATRY","REFERENCE_MATERIALS_MAPS","SMOKING_CESSATION","SPACE_ASTRONOMY","SPECIAL_EDUCATION","STREAMING_DOWNLOADABLE_VIDEO","TAX_PLANNING","TELEVISION","TEXT_MESSAGING_SMS","WIKIS","YEAR_712_EDUCATION"
);



